# Generated by Django 5.1.2 on 2024-11-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_datosextra_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='avatar',
            field=models.ImageField(blank=True, default='avatares/3d-illustration-person-with-sunglasses_23-2149436188.jpg', null=True, upload_to='avatares'),
        ),
    ]
