# Generated by Django 5.1.2 on 2024-11-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_datosextra_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='avatar',
            field=models.ImageField(blank=True, default='avatares/default-image.jpg', null=True, upload_to='avatares'),
        ),
    ]
