# Generated by Django 5.1.2 on 2024-11-01 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha_edicion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
