# Generated by Django 5.1.2 on 2024-11-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mascota_fecha_creacion_mascota_fecha_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='autor',
            field=models.CharField(default='Sin-Autor', max_length=100),
        ),
    ]
