# Generated by Django 5.1.2 on 2024-11-02 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mascota_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='mascotas/default-image.jpg', null=True, upload_to='mascotas')),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.mascota')),
            ],
        ),
    ]
